<?php
namespace app\modules\customers\api;

use Yii;

use yii\data\ActiveDataProvider;
use app\modules\customers\models\ItemData;
use yii\easyii\widgets\Fancybox;
use app\modules\customers\models\Category;
use app\modules\customers\models\Item;
use yii\widgets\LinkPager;

/**
 * Catalog module API
 * @package app\modules\customers\api
 *
 * @method static CategoryObject cat(mixed $id_slug) Get catalog category by id or slug
 * @method static array tree() Get catalog categories as tree
 * @method static array cats() Get catalog categories as flat array
 * @method static array items(array $options = []) Get list of items as ItemObject objects
 * @method static ItemObject get(mixed $id_slug) Get item object by id or slug
 * @method static mixed last(int $limit = 1, mixed $where = null) Get last items, use $where option for fetching items from special category
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */

class Catalog extends \yii\easyii\components\API
{
    private $_cats;
    private $_items;
    private $_adp;
    private $_item = [];
    private $_last;

    public function api_cat($id_slug)
    {
        if(!isset($this->_cats[$id_slug])) {
            $this->_cats[$id_slug] = $this->findCategory($id_slug);
        }
        return $this->_cats[$id_slug];
    }

    public function api_tree()
    {
        return Category::tree();
    }

    public function api_cats()
    {
        return Category::cats();
    }

    public function api_items($options = [])
    {
        if(!$this->_items){
            $this->_items = [];

            $query = Item::find()->with(['seo', 'category'])->status(Item::STATUS_ON);

            if(!empty($options['where'])){
                $query->andFilterWhere($options['where']);
            }
            if(!empty($options['orderBy'])){
                $query->orderBy($options['orderBy']);
            } else {
                $query->sortDate();
            }
            if(!empty($options['filters'])){
                $query = self::applyFilters($options['filters'], $query);
            }

            $this->_adp = new ActiveDataProvider([
                'query' => $query,
                'pagination' => !empty($options['pagination']) ? $options['pagination'] : []
            ]);

            foreach($this->_adp->models as $model){
                $this->_items[] = new ItemObject($model);
            }
        }
        return $this->_items;
    }

    public function api_last($limit = 1, $where = null)
    {
        if($limit === 1 && $this->_last){
            return $this->_last;
        }

        $result = [];

        $query = Item::find()->with('seo')->sortDate()->status(Item::STATUS_ON)->limit($limit);
        if($where){
            $query->andFilterWhere($where);
        }

        foreach($query->all() as $item){
            $result[] = new ItemObject($item);
        }

        if($limit > 1){
            return $result;
        }else{
            $this->_last = count($result) ? $result[0] : null;
            return $this->_last;
        }
    }

    public function api_get($id_slug)
    {
        if(!isset($this->_item[$id_slug])) {
            $this->_item[$id_slug] = $this->findItem($id_slug);
        }
        return $this->_item[$id_slug];
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        return $this->_adp ? LinkPager::widget(['pagination' => $this->_adp->pagination]) : '';
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }
    
    public static function applyFilters($filters, $query)
    {
        if(is_array($filters)){

            if(!empty($filters['country'])){
                $query->andFilterWhere(['=', 'country',$filters['country'] ]);

                unset($filters['country']);
            }
            if(!empty($filters['government'])){
                $query->andFilterWhere(['=', 'government',$filters['government'] ]);

                unset($filters['government']);
            }
            if(!empty($filters['city'])){
                $query->andFilterWhere(['=', 'city',$filters['city'] ]);

                unset($filters['city']);
            }
            if(!empty($filters['district'])){
                $query->andFilterWhere(['=', 'district',$filters['district'] ]);

                unset($filters['district']);
            }
            if(!empty($filters['product_id'])){
                //get all pharmacies for this product
                $sql = 'SELECT customer_id FROM customer_items where item_id='.$filters['product_id'];

                $allpharmacies = \yii\easyii\modules\catalog\models\Item::findBySql($sql)->asArray()->all();

                $data[]= null;
                foreach($allpharmacies as $key=>$value ){
                    $data[]=$value[customer_id].',';
                }
                $query->andFilterWhere(['in', 'item_id',$data ]);
                unset($filters['product_id']);
            }


        }
        return $query;
    }
    

    private function findCategory($id_slug)
    {
        $category = Category::find()->where(['or', 'category_id=:id_slug', 'slug=:id_slug'], [':id_slug' => $id_slug])->status(Item::STATUS_ON)->one();

        return $category ? new CategoryObject($category) : null;
    }

    private function findItem($id_slug)
    {
        if(!($item = Item::find()->where(['or', 'item_id=:id_slug', 'slug=:id_slug'], [':id_slug' => $id_slug])->status(Item::STATUS_ON)->one())){
            return null;
        }

        return new ItemObject($item);
    }
}